### PR TITLE
use Database.request_session to prevent from losing auth

### PR DESCRIPTION
**Pull request by JackWyj**

### CODE REVIEW

**Comment by JackWyj** [comment]
When passed (username, password) to Connection, i got `Exception: Code: 194, e.displayText() = DB::Exception: Password required for user default`.  The auth is stored in self.request_session, but it isn't used to post request.

**Comment by JackWyj** [comment]
sorry, didn't notice the another PR #45 , it solved the same problem.

**Comment by vavrusa** [comment]
This seems like a better solution than rewriting DSN, do you mind rebasing?

**Comment by JackWyj** [comment]
@vavrusa  seems it has been solved, and i have rebased mine, i have seen the updates about the problem. thx!

**Pull request closed without merging**
